### ISSUE TITLE
AuthUri is not correct

### ISSUE THREAD

**Issue by minzdrav** [SPIE-Worksphere/haystack-csharp#102]
Hi Haystack C# client team.
Currently AuthUri  build like this: AuthUri = new Uri(Uri, "/user/auth");
I think it's not correct for 2 reasons. I'll try to explain why.

If you setup the Haxon server https://haxall.io/, the default API URL will be "http://localhost:8080/api".
If you want to call any operation, you should add the operation name to that URL, like this: http://localhost:8080/api/about
But new Uri(Uri, "/user/auth") will produce a URI like this: http://localhost:8080/user/auth. As a result, the library doesn't call API. This is the first reason. 
The second reason - looks like "/user/auth" is a proprietary implementation of Haystack auth. And it's not compatible with the standard. Look here: https://project-haystack.org/doc/docHaystack/Auth
The client should call "about" operation. Maybe I'm wrong, but I can't find anything about "/user/auth" in the project Haystack documentation.

So, I suggest changing AuthUri generation to the following: apiUrl + "/about"
Example:
apiUrl = "http://localhost:8080/api"
authUrl = "http://localhost:8080/api/about"

What do you think? Is there any reason to keep "/user/auth"? Maybe we can use it only for some servers that don't support the standard way.

**Comment by minzdrav** [comment]
Sorry, I was wrong.
http://localhost:8080/user/auth is working fine for Haxon server. But http://localhost:8080/api/about is working too.
I still think "user/auth" is not standard and should be replaced.

**Comment by Breederveld** [comment]
Hi @minzdrav, unfortunately /api/about is not a standardized URL either; for example on SkySpark the correct URL would be /api/<project>/about. We could very well add an additional parameter to manually specify the auth URL. Do you have a preferred option here?

**Comment by minzdrav** [comment]
I'm overwriting AuthUri property if "user/auth" failed.
So, I have additional try-catch now :)
I'm ok with it. If you think "user/auth" is the best for compatibility - let's keep it.
If not, I would suggest changing the default to "api/about". Like on the project haystack site example.
![image](https://github.com/SPIE-Worksphere/haystack-csharp/assets/1764392/0a26a9ba-7f1e-4498-87ed-319dd1992dad)

**Comment by Breederveld** [comment]
As mentioned, the base /api/about won't work on all servers, but I've modified it to use the relative about page (for SkySpark this would be /api/<project>/about, for Niagra it's /api/about). Tested this on SkySpark without issues. A new NuGet version 2.0.27 is now available.
