### ISSUE TITLE
'BasicAuthenticator' not authenticating for (Tridium) 'Niagara' 4 (- 'HELLO' failed)

### ISSUE THREAD

**Issue by DennisVM-D2i** [SPIE-Worksphere/haystack-csharp#113]
It seems the 'WWW-Authenticate' header is not present within the response, so this line of code fails - for a Niagara 4 (- approx line # 47 of 'BasicAuthenticator.cs'):

                    auth = response.Headers.GetValues(_wwwAuthenticateHeader);

I'm guessing this might work:

                    // DVM: B:
                    // auth = response.Headers.GetValues(_wwwAuthenticateHeader);
                    if (response.Headers.Contains(_wwwAuthenticateHeader))
                    {
                        auth = response.Headers.GetValues(_wwwAuthenticateHeader);
                    }
                    else
                    {
                        return;
                        //auth = Array.Empty<string>();
                    }
                    // DVM: E:

Some environmental info:

  'productUri' = 'http://www.tridium.com/'
  'tz' = 'London'
  'moduleName' = 'nhaystack'
  'productName' = 'Niagara 4'
  'haystackVersion' = '2.0'
  'productVersion' = '4.12.1.16'
  'moduleVersion' = '3.2.0'
  'serverTime' = '29/11/2023 16:01:21 +00:00'
  'moduleUri' = 'https://bitbucket.org/richiemac_77/nhaystack'
  'serverBootTime' = '29/11/2023 11:37:06 +00:00'

(I created a 'DvmBasicAuthenticator' class to test - aka a modified copy of the 'BasicAuthenticator'.)

**Comment by Breederveld** [comment]
Hi @DennisVM-D2i, sorry for the late response, last year was a bit hectic.
I think your suggestion shouldn't break anything and if it helps an issue in Niagra 4, I am all for it. You are free to create a Pull Request with your suggested fix.

**Comment by Breederveld** [comment]
Hi @DennisVM-D2i , do you want to follow up on this issue, or is it fair to close it at this time?

**Comment by Breederveld** [comment]
Closed pending a response
